import { Inter } from "next/font/google";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import Nav from "../components/Shared/LocalNav";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.className} p-10 min-h-screen`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
